### ISSUE TITLE
Feature request: Better presentation for smaller values

### ISSUE THREAD

**Issue by senpl** [JDevZone/FillProgressLayout#11]
Currently all works nice for values above 60.
But for smaller values they not scale well. Sure we could increase values, but it would be nice if for smaller duration values progress and duration probably should scale to make it look nicer.
Current warkorond is multiply all values, but this workaround should not be required.

**Comment by JDevZone** [comment]
hi @senpl , actually i didn't get it properly (specifically that scale part) can you please explain it a bit more or you can just provide some illustration like gif or video.

**Comment by senpl** [comment]
Let's say you got progres with only 5 duration. When You using such small numbers it would be nice when view adjust make it look like it is duration 50 and steps: 50, 40, 30, 20 and 10. Just that for uset it would look nice. I hope it is now clearer. Just check for smaller duration to show them in nicer way.

**Comment by JDevZone** [comment]
okay, I see there may be some confusion regarding progress duration as it is designed to work with milliseconds i.e for 2 seconds it should be 2000. If we pass only 5 value for duration then it will be instant fill no animation at all. Any way i will add some safe checks or validation for that as well as some comments about it in next release.
