### ISSUE TITLE
setProgress not work in onViewCreated()

### ISSUE THREAD

**Issue by rny** [JDevZone/FillProgressLayout#15]
this line not work in onViewCreated() of Fragment
```
        progressbar.setProgress(50, false)
```

Reason:

```
initUI() called setProgress() with an animate before, any following setProgress() not work until animate finished.
```

Fix: the loading should not perform any animate

Line 137 inside initUI()
```
                setProgress(progress, false)
```

**Comment by rny** [comment]
```
setProgress(10, true) 
setProgress(50, false)
```

also, the above code should also have problem, the second call will have no effect.

I suggest add **endProgress** variable to remember animate finish position.

**Comment by JDevZone** [comment]
First of all Thanks @rny for pointing it out and really digging down to the cause and also suggesting the fix. This will be fixed in next release dropping soon.

**Comment by JDevZone** [comment]
Hi @rny ,This issue is fixed now in <a href = "https://github.com/JDevZone/FillProgressLayout/releases/tag/v0.0.7">this</a> release. so, closing this issue now.
