### ISSUE TITLE
Problems using in RecyclerView

### ISSUE THREAD

**Issue by developerGM** [JDevZone/FillProgressLayout#16]
If I use `FillProgressLayout` as a progress inside an item in `ViewHolder` in `RecyclerView`...there are some problems when the view is recycled on scroll up and down.
How can I solve this problem?

**Comment by JDevZone** [comment]
Hi @developerGM, can you please explain a bit more about the problems that you're facing so that we can get the context properly . If you have any general problem in recycler-view then you can visit <a href ="https://stackoverflow.com/a/40147626">this</a> stack link to improve overall performance.

**Comment by developerGM** [comment]
Hi @JDevZone, thanks for your reply.
My problem is not recyclerview performance.

I am a recyclerview with 10 items...Each item has `FillProgressLayout` inside as a child view. With a long press on item I am trying to start `FillProgressLayout` using `.progress(100, true)` using so the animation.

This is my use case:
- Click long press on 1° item -> start animation
- Click long press on 2° item -> start animation
- Scroll quickly on bottom of list and click on the last 2 items (9° and 10°) -> start animations
- When I scroll quickly on the top...the item 1° has the animation of 10° item because of course the view is recycled. 

How can I solve this problem?
Hope the description is more clear now

**Comment by JDevZone** [comment]
Hi @developerGM , this isn't a view specific issue as you can see <a href ="https://stackoverflow.com/a/50818440">here</a>. Animations are unable to survive after view recycling. But still in <a href="https://github.com/JDevZone/FillProgressLayout/releases/tag/v0.0.7">v0.07</a> animator is exposed for these kind of situations. A sample is attached as described on stack, hope it can help you out.



[FillRecycle.zip](https://github.com/JDevZone/FillProgressLayout/files/5874334/FillRecycle.zip)

**Comment by developerGM** [comment]
Thanks @JDevZone to expose animator, this is a very good first step.
In your example if I start progress on item 1...than scroll down and scroll up....item 1 is stopped on the last progress position.
Item 1 should never stop progress.

In my app, these items are some IOT device...on long press I start animation to show to user that physical device is running for 10secs.
So, when start item1 start animation for 10secs...and than scroll down and up, my user should see the progress animation always active if 10secs not endend.

**Comment by JDevZone** [comment]
Okay @developerGM, then you have to retain the views with their respective state means no recycling of views. But this will significantly affect the performance or can even leads to OOM. You can give it a shot for small number of items but as said earlier this defeats the purpose of recycler-view. You can have a look <a href = "https://stackoverflow.com/a/43191251"><strong>here</strong></a> to do so.
