### ISSUE TITLE
Impossible set custom color

### ISSUE THREAD

**Issue by developerGM** [JDevZone/FillProgressLayout#19]
How can I set a custom dynamic color from String (Exadecimal)
```
mProgress.setProgressBackgroundColor(Color.parseColor("#EEEEEE"));
mProgress.setProgressColor(Color.parseColor("#AAAAAA"));
```

**Comment by JDevZone** [comment]
Hi @developerGM , First of all Thank you for pointing this out and I'm glad to inform you that color Int support is now added in <a href="https://github.com/JDevZone/FillProgressLayout/releases/tag/v0.0.8">this<a> release. Happy Coding 😀

**Comment by developerGM** [comment]
Now is perfect. Thanks for your contribuite and for this library @JDevZone
