### ISSUE TITLE
How clear listeners?

### ISSUE THREAD

**Issue by hukjordanjanaq** [JDevZone/FillProgressLayout#21]
Nice library. Thanks for sharing it. i'd like to know if a can clear de listener. I was triying to set the progress 0 after it ends, but it crashed and i see the set function needs a non null listener.

<img width="551" alt="Captura de Pantalla 2021-06-09 a la(s) 17 39 47" src="https://user-images.githubusercontent.com/48919342/121438491-b1efa400-c949-11eb-90ff-0b3fedcb113f.png">

**Comment by JDevZone** [comment]
Hi @jordanjanaq , Thanks for pointing out this issue and detailed explanation. This issue is now fixed is this <a href='https://github.com/JDevZone/FillProgressLayout/releases/tag/v0.0.9'>release</a>. You can upgrade to latest version to use this.
