### ISSUE TITLE
Add support for reverse progress loading

### ISSUE THREAD

**Issue by aftabsikander** [JDevZone/FillProgressLayout#9]
It would be great if you can include progress indicator for reverse direction i.e progress being 100% in fill state with masking color over it, and when actual progress increases we reveal the actual image i.e going from 100 to 0 progress state. This is a enhancement request.

**Comment by JDevZone** [comment]
you can achieve this behaviour now (from v0.0.5). As default fill animation is optional now so you can set your predefined initial value and update it later according to your implementation.You can checkout sample app. I have updated it accordingly.
